import { createClient } from './client';

export type Profile = { id:string; email:string; full_name:string; avatar_url:string|null; cover_url:string|null; phone:string|null; role:string|null; account_type:string|null; is_active:boolean; created_at:string; updated_at:string };
export type Enterprise = { id:string; owner_id:string; name:string; slug:string; category:string|null; description:string|null; phone:string|null; email:string|null; website:string|null; address:string|null; city:string|null; province?:string|null; country?:string|null; logo_url:string|null; cover_url?:string|null; verified:boolean; created_at:string; updated_at:string };
export type Product = { id:string; owner_id:string; enterprise_id:string; name:string; slug:string|null; description:string|null; category:string; sub_category:string|null; price:string; unit:string|null; status:'Actif'|'Inactif'; availability:'Disponible'|'Rupture'|'Sur commande'; vendor_type:'Producteur'|'Grossiste'|'Importateur'|'Fabricant'|'Distributeur'; main_image_url:string|null; stock_qty:number; views:number; favorite_count?:number; created_at:string; updated_at:string };

async function getAuthenticatedUser(){const supabase=createClient();const {data:{user},error}=await supabase.auth.getUser();if(error)throw error;if(!user)throw new Error('Utilisateur non connecté');return{supabase,user};}
export async function getCurrentProfile(){const{supabase,user}=await getAuthenticatedUser();const{data,error}=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)throw error;return{user,profile:data as Profile|null};}
export async function updateCurrentProfile(values:Partial<Profile>){const{supabase,user}=await getAuthenticatedUser();const{data,error}=await supabase.from('profiles').update(values).eq('id',user.id).select('*').single();if(error)throw error;return data as Profile;}
export async function getMyEnterprises(){const{supabase,user}=await getAuthenticatedUser();const{data,error}=await supabase.from('enterprises').select('*').eq('owner_id',user.id).order('created_at',{ascending:false});if(error)throw error;return(data??[]).map((row:any)=>({...row,verified:Boolean(row.is_verified ?? row.verified)})) as Enterprise[];}
export async function getMyProducts(){const{supabase,user}=await getAuthenticatedUser();const{data,error}=await supabase.from('products').select('*').eq('vendor_id',user.id).order('created_at',{ascending:false});if(error)throw error;const ids=(data??[]).map((row:any)=>row.id);let viewCounts:Record<string,number>={};if(ids.length){const{data:views,error:viewError}=await supabase.from('product_views').select('product_id').in('product_id',ids);if(!viewError){viewCounts=(views??[]).reduce((acc:any,row:any)=>{acc[row.product_id]=(acc[row.product_id]??0)+1;return acc},{});}}return(data??[]).map((row:any)=>({id:row.id,owner_id:row.vendor_id,enterprise_id:row.enterprise_id??'',name:row.name,slug:row.name?.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')??null,description:row.description??null,category:row.category??'',sub_category:row.sub_category??null,price:row.price??'',unit:row.unit??null,status:row.is_active?'Actif':'Inactif',availability:row.stock_status==='En stock'||row.stock_status==='in_stock'?'Disponible':row.stock_status==='Sur commande'||row.stock_status==='on_order'?'Sur commande':'Rupture',vendor_type:row.vendor_type??'Grossiste',main_image_url:row.image_url??null,stock_qty:Number(row.stock_qty)||0,views:viewCounts[row.id]??0,favorite_count:row.favorite_count??0,created_at:row.created_at,updated_at:row.updated_at})) as Product[];}
export async function getMarketplaceProducts(){const supabase=createClient();const{data,error}=await supabase.from('products').select('id,name,description,category,price,unit,image_url,stock_status,stock_qty,rating,review_count,is_active,vendor_id,vendor_name,vendor_type,vendor_phone,vendor_email,vendor_city,vendor_verified,favorite_count,created_at,updated_at').eq('is_active',true).order('favorite_count',{ascending:false}).order('created_at',{ascending:false});if(error)throw error;return data??[];}
export async function getMyProductsCount(){const{supabase,user}=await getAuthenticatedUser();const{count,error}=await supabase.from('products').select('id',{count:'exact',head:true}).eq('vendor_id',user.id);if(error)throw error;return count??0;}
export async function getMyUnreadMessagesCount(){const{supabase,user}=await getAuthenticatedUser();const{count,error}=await supabase.from('messages').select('id',{count:'exact',head:true}).eq('receiver_id',user.id).eq('is_read',false);if(error)throw error;return count??0;}
export async function getMyFavoritesCount(){const{supabase,user}=await getAuthenticatedUser();const{count,error}=await supabase.from('favorites').select('id',{count:'exact',head:true}).eq('user_id',user.id);if(error)throw error;return count??0;}
export async function getMyViewsStats(){const{supabase,user}=await getAuthenticatedUser();const{data,error}=await supabase.from('product_views').select('product_id,viewed_at,products!inner(vendor_id)').eq('products.vendor_id',user.id);if(error)throw error;const rows=data??[];const now=new Date();const months=Array.from({length:6},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-(5-i),1);return{month:d.toLocaleDateString('fr-FR',{month:'short'}).replace('.','').replace(/^./,c=>c.toUpperCase()),year:d.getFullYear(),monthIndex:d.getMonth()};});const chart=months.map(m=>({month:m.month,value:rows.filter((r:any)=>{const d=new Date(r.viewed_at);return d.getFullYear()===m.year&&d.getMonth()===m.monthIndex}).length}));return{total:rows.length,chart};}

const SUPPLIER_TYPES = ['Producteur','Grossiste','Importateur','Fabricant','Distributeur'] as const;
type SupplierType = typeof SUPPLIER_TYPES[number];
type DbStockStatus = 'En stock'|'Stock limité'|'Rupture de stock';
function toDbStockStatus(availability:Product['availability']):DbStockStatus{return availability==='Disponible'?'En stock':availability==='Sur commande'?'Stock limité':'Rupture de stock';}
export async function createProduct(input:Omit<Product,'id'|'owner_id'|'created_at'|'updated_at'|'views'>){const{supabase,user}=await getAuthenticatedUser();const enterprises=await getMyEnterprises();const enterprise=enterprises.find(item=>item.id===input.enterprise_id);if(!enterprise)throw new Error('Entreprise invalide ou non autorisée.');if(!input.price?.trim())throw new Error('Le prix est obligatoire.');if(!SUPPLIER_TYPES.includes(input.vendor_type as SupplierType))throw new Error('Type de fournisseur invalide.');const stockQty=Math.max(0,Number(input.stock_qty)||0);const{data,error}=await supabase.from('products').insert({name:input.name,description:input.description,price:input.price.trim(),unit:input.unit??'',category:input.category,sub_category:input.sub_category??null,enterprise_id:enterprise.id,vendor_id:user.id,vendor_name:enterprise.name,vendor_type:input.vendor_type,vendor_phone:enterprise.phone,vendor_email:enterprise.email,vendor_city:enterprise.city,vendor_verified:enterprise.verified,city:enterprise.city,image_url:input.main_image_url,alt_text:input.name,is_active:input.status==='Actif',stock_status:toDbStockStatus(input.availability),stock_qty:stockQty}).select('*').single();if(error)throw error;if(input.main_image_url){const{error:imageError}=await supabase.from('product_images').insert({product_id:data.id,image_url:input.main_image_url,alt_text:input.name,sort_order:0});if(imageError)throw imageError;}return{...input,id:data.id,owner_id:user.id,enterprise_id:enterprise.id,stock_qty:stockQty,views:0,created_at:data.created_at,updated_at:data.updated_at} as Product;}
export async function updateProduct(id:string,values:Partial<Product>){const{supabase,user}=await getAuthenticatedUser();const enterprises=await getMyEnterprises();const enterprise=values.enterprise_id?enterprises.find(item=>item.id===values.enterprise_id):undefined;const patch:Record<string,unknown>={};if(values.name!==undefined)patch.name=values.name;if(values.description!==undefined)patch.description=values.description;if(values.price!==undefined){if(!values.price?.trim())throw new Error('Le prix est obligatoire.');patch.price=values.price.trim();}if(values.unit!==undefined)patch.unit=values.unit??'';if(values.category!==undefined)patch.category=values.category;if(values.sub_category!==undefined)patch.sub_category=values.sub_category??null;if(values.main_image_url!==undefined)patch.image_url=values.main_image_url;if(values.stock_qty!==undefined)patch.stock_qty=Math.max(0,Number(values.stock_qty)||0);if(values.status!==undefined)patch.is_active=values.status==='Actif';if(values.availability!==undefined)patch.stock_status=toDbStockStatus(values.availability);if(values.vendor_type!==undefined){if(!SUPPLIER_TYPES.includes(values.vendor_type as SupplierType))throw new Error('Type de fournisseur invalide.');patch.vendor_type=values.vendor_type;}if(enterprise){patch.enterprise_id=enterprise.id;patch.vendor_name=enterprise.name;patch.vendor_phone=enterprise.phone;patch.vendor_email=enterprise.email;patch.vendor_city=enterprise.city;patch.vendor_verified=enterprise.verified;patch.city=enterprise.city;}const{data,error}=await supabase.from('products').update(patch).eq('id',id).eq('vendor_id',user.id).select('*').single();if(error)throw error;if(values.main_image_url!==undefined){await supabase.from('product_images').delete().eq('product_id',id).eq('sort_order',0);if(values.main_image_url){const{error:imageError}=await supabase.from('product_images').insert({product_id:id,image_url:values.main_image_url,alt_text:values.name??data.name,sort_order:0});if(imageError)throw imageError;}}return{...values,id:data.id,owner_id:user.id,enterprise_id:data.enterprise_id,stock_qty:Number(data.stock_qty)||0,views:0,created_at:data.created_at,updated_at:data.updated_at} as Product;}
export async function deleteProduct(id:string){const{supabase,user}=await getAuthenticatedUser();const{error}=await supabase.from('products').delete().eq('id',id).eq('vendor_id',user.id);if(error)throw error;}
export async function uploadImage(file:File,folder:'products'|'enterprise'|'profile'){const{supabase,user}=await getAuthenticatedUser();const extension=file.name.split('.').pop()?.toLowerCase()||'jpg';const bucket=folder==='products'?'article-images':'profile-photos';const path=`${user.id}/${folder}/${crypto.randomUUID()}.${extension}`;const{error}=await supabase.storage.from(bucket).upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl;}