'use client';
import React, { useEffect, useRef, useState } from 'react';
import { CheckCircleIcon, ChatBubbleOvalLeftIcon, BuildingOfficeIcon, ArrowTrendingUpIcon } from '@heroicons/react/24/outline';
import { createClient } from '@/lib/supabase/client';
import { getMyProductsCount, getMyUnreadMessagesCount, getMyFavoritesCount, getMyViewsStats } from '@/lib/supabase/database';
interface DashboardHomeProps { onNavigate?: (tab: string) => void; }
const activities = [
  { id: 1, text: "Votre produit 'Café Robusta' a été approuvé", time: 'Il y a 2 heures', icon: CheckCircleIcon, iconColor: 'text-green-400', iconBg: 'bg-green-400/10' },
  { id: 2, text: 'Nouveau message de Jean Mutombo', time: 'Il y a 3 heures', icon: ChatBubbleOvalLeftIcon, iconColor: 'text-blue-400', iconBg: 'bg-blue-400/10' },
];
function LineChart({data}:{data:{month:string;value:number}[]}) {
  const pathRef = useRef<SVGPathElement>(null);
  useEffect(() => { const timer = window.setTimeout(() => pathRef.current?.classList.add('animated'), 300); return () => window.clearTimeout(timer); }, []);
  const w=500,h=160,padX=36,padY=16,chartW=w-padX*2,chartH=h-padY*2-16,maxVal=Math.max(1,...data.map(d=>d.value));
  const points=data.map((d,i)=>({x:padX+(i/Math.max(1,data.length-1))*chartW,y:padY+chartH-(d.value/maxVal)*chartH}));
  const pathD=points.reduce((acc,p,i)=>{if(i===0)return `M ${p.x} ${p.y}`;const prev=points[i-1],cpX=(prev.x+p.x)/2;return `${acc} C ${cpX} ${prev.y}, ${cpX} ${p.y}, ${p.x} ${p.y}`;},'');
  const areaD=points.length?`${pathD} L ${points[points.length-1].x} ${padY+chartH} L ${points[0].x} ${padY+chartH} Z`:'';
  const labels=[0,1,2,3,4,5].map(i=>Math.round(maxVal-(maxVal/5)*i));
  return <div className="w-full overflow-x-auto"><svg viewBox={`0 0 ${w} ${h}`} className="w-full" style={{minWidth:280}}><defs><linearGradient id="chartGrad" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#F5A623" stopOpacity="0.25"/><stop offset="100%" stopColor="#F5A623" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4,5].map(i=><line key={i} x1={padX} y1={padY+(chartH/5)*i} x2={w-padX} y2={padY+(chartH/5)*i} stroke="rgba(255,255,255,0.06)" strokeWidth="1"/>)}{labels.map((v,i)=><text key={i} x={padX-6} y={padY+(chartH/5)*i+4} textAnchor="end" fontSize="9" fill="rgba(255,255,255,0.3)">{v}</text>)}{areaD&&<path d={areaD} fill="url(#chartGrad)"/>}<path ref={pathRef} d={pathD} fill="none" stroke="#F5A623" strokeWidth="2.5" strokeLinecap="round" className="chart-line-path"/>{points.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="4" fill="#F5A623" stroke="#1A1A1A" strokeWidth="2"/>)}{data.map((d,i)=><text key={`${d.month}-${i}`} x={points[i]?.x??0} y={h-2} textAnchor="middle" fontSize="10" fill="rgba(255,255,255,0.4)">{d.month}</text>)}</svg></div>;
}
export default function DashboardHome({onNavigate}:DashboardHomeProps){
  const [productCount,setProductCount]=useState<number|null>(null),[messageCount,setMessageCount]=useState<number|null>(null),[favoriteCount,setFavoriteCount]=useState<number|null>(null),[viewStats,setViewStats]=useState<{total:number;chart:{month:string;value:number}[]}>({total:0,chart:[]}),[statsError,setStatsError]=useState(false);
  const supabase=createClient();
  useEffect(()=>{let mounted=true;let channel:ReturnType<typeof supabase.channel>|null=null;const loadStats=async()=>{try{const[products,messages,favorites,views]=await Promise.all([getMyProductsCount(),getMyUnreadMessagesCount(),getMyFavoritesCount(),getMyViewsStats()]);if(!mounted)return;setProductCount(products);setMessageCount(messages);setFavoriteCount(favorites);setViewStats(views);setStatsError(false)}catch{if(mounted)setStatsError(true)}};const subscribe=async()=>{const{data,error}=await supabase.auth.getUser();if(!mounted||error||!data.user)return;channel=supabase.channel(`dashboard-stats:${data.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'products',filter:`vendor_id=eq.${data.user.id}`},()=>void loadStats()).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`receiver_id=eq.${data.user.id}`},()=>void loadStats()).on('postgres_changes',{event:'*',schema:'public',table:'favorites',filter:`user_id=eq.${data.user.id}`},()=>void loadStats()).on('postgres_changes',{event:'INSERT',schema:'public',table:'product_views'},()=>void loadStats()).subscribe()};void loadStats();void subscribe();return()=>{mounted=false;if(channel)void channel.unsubscribe()}},[supabase]);
  return <div><div className="mb-6"><h1 className="text-xl font-extrabold text-foreground mb-1">Bienvenue, Christian Yukuwansompa 👋</h1><p className="text-sm text-muted-foreground">Voici un aperçu de votre activité sur EmpireKongo.</p></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6"><div className="stat-card"><p className="text-xs text-muted-foreground font-medium mb-3">Produits</p><p className="text-3xl font-extrabold text-foreground mb-1">{productCount===null?'—':productCount}</p><button onClick={()=>onNavigate?.('products')} className="text-xs text-primary hover:underline text-left">{statsError?'Vérifier mes produits':'Voir mes produits'}</button></div><div className="stat-card"><p className="text-xs text-muted-foreground font-medium mb-3">Vues</p><p className="text-3xl font-extrabold text-foreground mb-1">{viewStats.total.toLocaleString('fr-FR')}</p><p className="text-xs text-green-400 flex items-center gap-1"><ArrowTrendingUpIcon className="w-3.5 h-3.5"/>Données réelles</p></div><div className="stat-card"><p className="text-xs text-muted-foreground font-medium mb-3">Messages</p><p className="text-3xl font-extrabold text-primary mb-1">{messageCount===null?'—':messageCount}</p><p className="text-xs text-muted-foreground">Non lus</p></div><div className="stat-card"><p className="text-xs text-muted-foreground font-medium mb-3">Favoris</p><p className="text-3xl font-extrabold text-foreground mb-1">{favoriteCount===null?'—':favoriteCount}</p><p className="text-xs text-muted-foreground">Total</p></div></div><div className="grid grid-cols-1 lg:grid-cols-3 gap-4"><div className="lg:col-span-2 bg-card border border-border rounded-xl p-4"><div className="flex items-center justify-between mb-3"><div><h3 className="font-bold text-sm text-foreground">Vues de vos produits</h3><p className="text-xs text-muted-foreground">(6 derniers mois)</p></div></div><LineChart data={viewStats.chart.length?viewStats.chart:Array.from({length:6},(_,i)=>({month:['Jan','Fév','Mar','Avr','Mai','Juin'][i],value:0}))}/></div><div className="bg-card border border-border rounded-xl p-4 flex flex-col"><h3 className="font-bold text-sm text-foreground mb-4">Activité récente</h3><div className="flex flex-col gap-4 flex-1">{activities.map(act=><div key={act.id} className="flex items-start gap-3"><div className={`w-8 h-8 rounded-lg ${act.iconBg} flex items-center justify-center shrink-0 mt-0.5`}><act.icon className={`w-4 h-4 ${act.iconColor}`}/></div><div className="flex-1 min-w-0"><p className="text-xs text-foreground leading-relaxed">{act.text}</p><p className="text-[10px] text-muted-foreground mt-1">{act.time}</p></div></div>)}</div><button className="mt-4 w-full py-2.5 rounded-lg border border-border text-xs font-semibold text-muted-foreground hover:text-foreground hover:border-primary/40 transition-colors">Voir toutes les activités</button></div></div></div>;
}